<?php
// actions/generate_pdf_report.php

require '../db.php';
require 'grading_helper.php'; // Your custom grading logic
require 'fpdf.php';           // FPDF Library

// Security & Input Check
if ($_SERVER['REQUEST_METHOD'] !== 'POST' || !isset($_POST['modules'])) {
    die("Error: No modules selected.");
}

$class_id = $_POST['class_id'];
$module_ids = $_POST['modules']; // Array of assignment IDs

// 1. Fetch Class Name
$stmt = $pdo->prepare("SELECT class_name FROM teacher_classes WHERE id = ?");
$stmt->execute([$class_id]);
$class_name = $stmt->fetchColumn();

// 2. Fetch Selected Modules (Titles)
$placeholders = implode(',', array_fill(0, count($module_ids), '?'));
$stmt = $pdo->prepare("SELECT id, title FROM assignments WHERE id IN ($placeholders)");
$stmt->execute($module_ids);
$modules = $stmt->fetchAll(PDO::FETCH_KEY_PAIR); // [id => title]

// 3. Fetch Students in Class
$stmt = $pdo->prepare("
    SELECT s.id, s.name 
    FROM students s
    JOIN class_enrollments ce ON s.id = ce.student_id
    WHERE ce.class_id = ?
    ORDER BY s.name ASC
");
$stmt->execute([$class_id]);
$students = $stmt->fetchAll();

// 4. Fetch Marks for these modules
$stmt = $pdo->prepare("
    SELECT student_id, assignment_id, final_percentage 
    FROM marks 
    WHERE assignment_id IN ($placeholders)
");
$stmt->execute($module_ids);
$raw_marks = $stmt->fetchAll();

// Re-organize marks: $marksMap[student_id][assignment_id] = percentage
$marksMap = [];
foreach ($raw_marks as $m) {
    $marksMap[$m['student_id']][$m['assignment_id']] = $m['final_percentage'];
}

// --- FPDF GENERATION ---

class ReportPDF extends FPDF {
    function Header() {
        $this->SetFont('Arial', 'B', 16);
        $this->Cell(0, 10, 'Student Performance Report', 0, 1, 'C');
        $this->SetFont('Arial', '', 12);
        $this->Cell(0, 8, $GLOBALS['class_name'], 0, 1, 'C');
        $this->Line(10, 30, 200, 30);
        $this->Ln(10);
    }

    function Footer() {
        $this->SetY(-15);
        $this->SetFont('Arial', 'I', 8);
        $this->Cell(0, 10, 'Generated by SchoolSync on ' . date('Y-m-d'), 0, 0, 'C');
    }
}

$pdf = new ReportPDF();
$pdf->AddPage();
$pdf->SetFont('Arial', '', 12);

// Loop through each student
foreach ($students as $student) {
    $sid = $student['id'];
    
    // Student Header
    $pdf->SetFont('Arial', 'B', 14);
    $pdf->SetFillColor(230, 230, 230);
    $pdf->Cell(0, 10, 'Student: ' . utf8_decode($student['name']), 1, 1, 'L', true);
    
    // Table Header
    $pdf->SetFont('Arial', 'B', 10);
    $pdf->Cell(110, 8, 'Module', 1);
    $pdf->Cell(30, 8, 'Mark (%)', 1);
    $pdf->Cell(20, 8, 'Grade', 1);
    $pdf->Cell(30, 8, 'GPV', 1, 1);
    
    $pdf->SetFont('Arial', '', 10);

    $total_gpv = 0;
    $count = 0;

    // Loop through selected modules for this student
    foreach ($modules as $aid => $title) {
        $mark = $marksMap[$sid][$aid] ?? null; // Get mark or null
        
        // Use your grading_helper.php logic
        $details = getGradeDetails($mark); // Returns ['grade' => 'A', 'gpv' => 4.0]
        
        // Display Row
        $pdf->Cell(110, 8, utf8_decode($title), 1);
        $pdf->Cell(30, 8, ($mark !== null ? $mark : '-'), 1);
        $pdf->Cell(20, 8, $details['grade'], 1);
        $pdf->Cell(30, 8, number_format($details['gpv'], 2), 1, 1);

        // Accumulate for Final GPA
        // We only count assignments that have been graded (numeric marks)
        if (is_numeric($mark)) {
            $total_gpv += $details['gpv'];
            $count++;
        }
    }

    // Final GPA Calculation
    $final_gpa = ($count > 0) ? ($total_gpv / $count) : 0.00;

    // Summary Row
    $pdf->SetFont('Arial', 'B', 11);
    $pdf->Cell(160, 10, 'Final GPA', 1, 0, 'R');
    $pdf->SetFillColor(255, 255, 200); // Yellow highlight
    $pdf->Cell(30, 10, number_format($final_gpa, 2), 1, 1, 'C', true);

    $pdf->Ln(10); // Space between students
}

// Output PDF
$pdf->Output('I', 'Report_' . preg_replace('/[^a-zA-Z0-9]/', '_', $class_name) . '.pdf');
?>